apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      timeInterval: "15s"

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    isDefault: false
    jsonData:
      httpMethod: GET
      # Corréler les traces avec les profils Pyroscope
      tracesToProfiles:
        datasourceUid: pyroscope
        tags:
          - key: service.name
            value: service_name
        profileTypeId: process_cpu:cpu:nanoseconds:cpu:nanoseconds
        customQuery: false
      serviceMap:
        datasourceUid: prometheus

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    url: http://pyroscope:4040
    isDefault: false
